// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.jarvis.grpc.proto;

public interface MyReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jarvis.grpc.MyReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string username = 1;</code>
   */
  String getUsername();
  /**
   * <code>string username = 1;</code>
   */
  com.google.protobuf.ByteString
      getUsernameBytes();
}
