// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.jarvis.grpc.proto;

public interface MyRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.jarvis.grpc.MyResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string realName = 1;</code>
   */
  String getRealName();
  /**
   * <code>string realName = 1;</code>
   */
  com.google.protobuf.ByteString
      getRealNameBytes();
}
